### ISSUE TITLE
Logger prerequisite

### ISSUE THREAD

**Issue by ellis** [TobiasTheViking/googledriveannex#1]
When I run `python2 googledriveannex.py`, I get the following output:

```
No handlers could be found for logger "oauth2client.util"
Go to the following link in your browser: ...
Enter verification code: ...
Traceback (most recent call last):
  File "googledriveannex.py", line 287, in <module>
    main()
  File "googledriveannex.py", line 245, in main
    folder = findInFolder(ANNEX_HASH_1, ANNEX_FOLDER)
  File "googledriveannex.py", line 123, in findInFolder
    common.log("Failure on: " + subject)
```

I'm not familiar with python, but it looks like I should install a logger.  Could you perhaps update the list of prerequisites to account for needing a logger library too?

**Comment by TobiasTheViking** [comment]
The logger issue is just a warning, the crash is unrelated.

Thanks for reporting this. Fix pushed.
